#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

echo "Running post-update hook"
exec git apply patches/.travis.patch patches/prepare_vscode.patch
